name: Pylint

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint sewar
        pip install -e ".[dev]"
    - name: Analysing the code with pylint
      run: |
        pylint hyperparameter_searcher --errors-only